baseURL = "https://cypher-z.github.io"
languageCode = "en-us"
title = "Yiming Zhang"
googleAnalytics = ""
publishDir = "docs"
timeout=3000

[params]
  subtitle= "PhD Student"
  interests="Network Security, Data Driven Security"
  blog="http://netsec.ccert.edu.cn/people/zym17"

[[params.affilation]]
  name = "Dept. of Computer Science and Technology, Tsinghua University"
  position = "PhD Student"
  contact = "zhangyim17@mails.tsinghua.edu.cn"

[[params.affilation]]
  name = "Network & Information Security Lab (NISL), Tsinghua University"
  position = "Research Assistant"
  contact = "FIT 4-204, Tsinghua University, Beijing 100084, P.R.China"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/Cypher-Z"


[[params.introduction.paragraph]]
  text="""I'm a Ph.D. candidate in the Department of Computer Science and Technology at Tsinghua University, advised by Prof. Haixin Duan. 
  Currently, my research studies network security, with a particular interest in data-driven security and protocol security. 
  I received my Bachelor degree in Fundamental Science of Mathematics and Physics from Tsinghua Univeristy in 2017. 
   """


[[params.publications]]
  year="Conference"
  
  [[params.publications.paper]]
    name = "From WHOIS to WHOWAS: A Large-Scale Measurement Study of Domain Registration Privacy under the GDPR"
    authors = "Chaoyi Lu, Baojun Liu, **Yiming Zhang**, Zhou Li, Fenglu Zhang, Haixin Duan, Ying Liu, Joann Qiongna Chen, Jinjin Liang, Zaifeng Zhang, Shuang Hao and Min Yang"
    dest  = "**[NDSS' 21]**"
	link = "/ndss21.pdf"

  [[params.publications.paper]]
    name = "Lies in the Air: Characterizing Fake-base-station Spam Ecosystem in China"
    authors = "**Yiming Zhang**, Baojun Liu, Chaoyi Lu, Zhou Li, Haixin Duan, Shuang Hao, Mingxuan Liu, Ying Liu, Dong Wang and Qiang Li"
    dest  = "**[ACM CCS' 20]**"
	link = "/ccs20.pdf"
	blog_link = "https://github.com/Cypher-Z/FBS_SMS_Dataset"

  [[params.publications.paper]]
    name = "Argot: Generating Adversarial Readable Chinese Texts"
    authors = "Zihan Zhang, Mingxuan Liu, Chao Zhang, **Yiming Zhang**, Zhou Li, Qi Li, Haixin Duan and Donghong Sun"
    dest  = "**[IJCAI' 20]**"
    link = "/ijcai20.pdf"

  [[params.publications.paper]]
    name = "TraffickStop: Detecting and Measuring Illicit Traffic Monetization Through Large-scale DNS Analysis"
	authors = "Baojun Liu, Zhou Li, Peiyuan Zong, Chaoyi Lu, Haixin Duan, Ying Liu, Sumayah Alrwais, Xiaofeng Wang, Shuang Hao, Yaoqi Jia, **Yiming Zhang**, Kai Chen and Zaifeng Zhang"
	dest = "**[Euro S&P' 19]**"
	link = "/eurosp19.pdf"

[[params.publications]]
  year="Journals"

  [[params.publications.paper]]
		name = "教育类官网推广感染研究"
		authors = "王郁，**张一铭**, 张甲，段海新"
		dest  = "**通信学报**,2018.9, 39(Z1): 78~85"

[[params.services]]
  content="External Reviewer"
  [[params.services.item]]
		dest = "ESORICS’18,19; ICICS’19; DSN’20; NDSS'20,22"
  


